version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: navi-postgres
    environment:
      POSTGRES_DB: navi_db
      POSTGRES_USER: navi_user
      POSTGRES_PASSWORD: navi_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - navi-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U navi_user -d navi_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  navi-network:
    driver: bridge
